### PR TITLE
shift reg

### PR DESCRIPTION
**Pull request by Skanda-Prasad**

### CODE REVIEW

**Comment by skudlur** [comment]
Hey @Skanda-Prasad, great job on the test bench! But I was just wondering about the arbitrary time delays that you have given, they seem haphazard. Can you explain them a little?

**Comment by Skanda-Prasad** [comment]
Oh, I just gave random time delays. I did not realise that 12 seconds is a long time. Sorry about that! I will change and reduce it.

**Comment by skudlur** [comment]
No no, the time delay is not an issue. I was just wondering why you gave 12 seconds that is all. Don't worry, the testbench looks good!

**Comment by skudlur** [comment]
!bounty 80

**Comment by Skanda-Prasad** [comment]
Oh okay. Thank you!!!

**Pull request closed without merging**
