### PR TITLE
this commit consists of the circuit code

### PR DESCRIPTION
**Pull request by JoyenBenitto**
had circuit data flow style ,structural and its test bench

### CODE REVIEW

**Comment by suhaskv1** [comment]
Yes, we are reviewing the code. Stay put for updates!

**Comment by suhaskv1** [comment]
Hey, @JoyenBenitto, can you give a newline after `endmodule` for all the files that you have made.

**Comment by skudlur** [comment]
Also, there are a few syntax changes. Please rectify and make the changes.

**Comment by JoyenBenitto** [comment]
few updates on syntax and line

**Comment by skudlur** [comment]
Good PR!

**Comment by skudlur** [comment]
!bounty 60

**Pull request closed without merging**
